apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-full-access-clusterrole
rules:
- apiGroups: ["", "*"] 
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-full-access-binding
subjects:
- kind: Group
  name: eks-full-access-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-full-access-clusterrole
  apiGroup: rbac.authorization.k8s.io
