name: "[1] CONTINUOUS INTEGRATION"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  TFlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Terraform Lint 
        run : | 
          cd terraform
          tflint

  ValidateAndPlan:
    runs-on: ubuntu-latest
    environment: terraform-aws-infra-webapp-secrets-env
    needs: 
      - TFlint
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

      - name: Terraform Validate
        run : | 
          cd terraform
          terraform init -input=false
          terraform validate -no-color
      - name: Terraform Plan
        run : | 
          cd terraform
          terraform plan -out plan.out -input=false

          echo "==> Uploading plan.out to S3 Bucket"
          aws s3 cp plan.out s3://alissonpdc-terraform-remote-state-bucket/terraform-aws-infra-webapp/