name: "[1] CONTINUOUS INTEGRATION"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ValidateAndPlan:
    runs-on: ubuntu-latest
    environment: terraform-aws-infra-webapp-secrets-env
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

      - name: Terraform Validate
        run : | 
          ls -la
          cd terraform
          ls -ls
          pwd
          terraform init
          terraform validate
      - name: Terraform Plan
        run : | 
          terraform plan -out plan.out
          aws s3 cp plan.out s3://alissonpdc-terraform-remote-state-bucket/terraform-aws-infra-webapp/