name: "[1] CONTINUOUS INTEGRATION"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ValidateAndPlan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: "${{ secrets.AWS_OIDC_ROLE }}"

      - name: Terraform Validate
        run : | 
          cd terraform
          terraform init
          terraform validate
      - name: Terraform Plan
        run : | 
          terraform plan -out plan.out
          aws s3 cp plan.out s3://"${{ secrets.AWS_BUCKET_REMOTE_STATE }}"/terraform-aws-infra-webapp/