name: "[3] DESTROY"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    environment: terraform-aws-infra-webapp-secrets-env
    steps:
      - uses: actions/checkout@v3
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

      - name: Terraform Plan
        run : | 
          cd terraform
          terraform init
          terraform plan -out destroy.out -input=false -destroy
      
      - name: Upload destroy.out
        run : | 
          echo "==> Uploading destroy.out to S3 Bucket"
          aws s3 cp terraform/destroy.out s3://alissonpdc-terraform-remote-state-bucket/terraform-aws-infra-webapp/

  TerraformDestroy:
    runs-on: ubuntu-latest
    environment: terraform-aws-infra-webapp-secrets-env
    needs: 
      - TerraformPlan
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

      - name: Download destroy.out
        run : | 
          echo "==> Downloading destroy.out from S3 Bucket"
          cd terraform
          aws s3api get-object --bucket alissonpdc-terraform-remote-state-bucket --key terraform-aws-infra-webapp/destroy.out destroy.out

      - name: Terraform Deploy
        run : | 
          cd terraform
          terraform init
          terraform apply destroy.out
        
